### ISSUE TITLE
Root Cause Analysis of unprocessed tx

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge#105]
https://etherscan.io/tx/0xca1e73891a0634867e14f42ac3c48c50f5b6ce95d51ff3f5c107844f4437f9b4

**Comment by yrashk** [comment]
In order to make sure I can do the best job here, can you please provide your specific expectations and how did they fail?

Also, a specific version of the bridge used will be helpful to have.

**Comment by rstormsf** [comment]
1 updated bridge node successfully processed it.

2 other old May 10th bridge rust node missed it.

**Comment by yrashk** [comment]
Ok, so you expected old bridge to work, but it didn't. You also expected the new bridge to work, and it did. Correct?

**Comment by rstormsf** [comment]
CollectedSignatures event was fired and the node that was responsible for  it - send a tx to Home bridge which failed
https://poaexplorer.com/tx/0x669b271f4526ea44fc3a62986604a9105c00d8a739554eef45c0a4f0ad1de7fb

**Comment by yrashk** [comment]
Problem was resolved. Relaying the analysis by @rstormsf: default gas limit for withdraw_relay ws set to 100k in the configuration, updating it to 300k resolved the issue.

**Comment by rstormsf** [comment]
yes, also if the bridge was using `estimateGas` without  relying  on those hard coded values, we wouldn't have  this issue as well
