### ISSUE TITLE
Account invalid error when using single validator

### ISSUE THREAD

**Issue by kpulkit29** [poanetwork/poa-bridge#117]
env RUST_LOG=info ./poa-bridge/target/release/bridge --config config.toml --database db.toml
INFO:bridge: Parsing cli arguments
INFO:bridge: Loading config
INFO:bridge: Starting event loop
INFO:bridge: Home rpc host https://sokol.poa.network
INFO:bridge: Foreign rpc host https://kovan.infura.io/mew
INFO:bridge: Establishing connection:
INFO:bridge: using RPC connection
WARN:bridge: Can't establish an RPC connection: Error(AccountError(InvalidAccount), State { next_error: None, backtrace: None })
account error InvalidAccount

I am using a single validator config.toml and password.txt are in same folder

**Comment by akolotov** [comment]
Could you share your `config.toml`? Please make sure that keystore file exists and can be accessible by the user who runs `bridge` process.

**Comment by kpulkit29** [comment]
The keystore file is in the keys folder.Do i have to name it to
keystore.json or default name would work

By the way here is the config.toml file

keystore = "keys"

[home]
account = "0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D"
required_confirmations = 0
rpc_host = "https://sokol.poa.network"
rpc_port = 443
password = "password.txt"

[foreign]
account = "0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a"
required_confirmations = 0
rpc_host = "https://kovan.infura.io/mew"
rpc_port = 443
password = "password.txt"

[authorities]
accounts = [
  "0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a"
]
required_signatures = 1

[transactions]
deposit_relay = { gas = 3000000, gas_price = 1000000000 }
withdraw_relay = { gas = 3000000, gas_price = 1000000000 }
withdraw_confirm = { gas = 3000000, gas_price = 1000000000 }

**Comment by akolotov** [comment]
`keys` directory contains one keystore file, right? But you are trying to use two accounts `0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D` and `0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a`. That's why you are getting error when trying to decode the private key for one of these accounts - there are no corresponding file.
You need to use one account - the same which is used in validators list during bridge contracts deployment.

BTW, which version of `bridge` process are you using?

**Comment by kpulkit29** [comment]
Thanks I changed it to the same address but now I get this error
env RUST_LOG=info ./poa-bridge/target/release/bridge --config config.toml
--database db.toml
INFO:bridge: Parsing cli arguments
INFO:bridge: Loading config
INFO:bridge: Starting event loop
INFO:bridge: Home rpc host https://sokol.poa.network
<https://rb.tc/3K01Z#https://sokol.poa.network>
INFO:bridge: Foreign rpc host https://kovan.infura.io/mew
<https://rb.tc/3K01-#https://kovan.infura.io/mew>
INFO:bridge: Establishing connection:
INFO:bridge:   using RPC connection
WARN:bridge: Can't establish an RPC connection:
Error(AccountError(InvalidAccount), State { next_error: None, backtrace:
None })
account error InvalidAccount

check/sokol-kovan-bridge/poa2
➜ env RUST_LOG=info ./poa-bridge/target/release/bridge --config config.toml
--database db.toml
INFO:bridge: Parsing cli arguments
INFO:bridge: Loading config
INFO:bridge: Starting event loop
INFO:bridge: Home rpc host https://sokol.poa.network
<https://rb.tc/3K01_#https://sokol.poa.network>
INFO:bridge: Foreign rpc host https://kovan.infura.io/mew
INFO:bridge: Establishing connection:
INFO:bridge:   using RPC connection
INFO:bridge: Acquiring home & foreign chain ids
INFO:bridge: Home chain ID: 77 Foreign chain ID: 42
INFO:bridge: Reading the database
Cannot parse database

**Comment by kpulkit29** [comment]
Here is the db.toml file
{
    "homeBridge": {
        "address": "0xE04d6A4a971d242aC246637843431E32269DBeC4",
        "deployedBlockNumber": null
    },
    "foreignBridge": {
        "address": "0x74c2d89A4E15061c6C24a7f8cb11BE43e24464e0",
        "deployedBlockNumber": 8238408
    },
    "erc677": {
        "address": "0x5D27eE11662e2E2056DF25D7FB1FC4C20729997e"
    }
}

**Comment by kpulkit29** [comment]
The home bridge address is null.But everything went fine while deployment.

**Comment by akolotov** [comment]
> I made the db.toml file just as given in the readme

You need to use another format for the database described in https://github.com/poanetwork/poa-bridge#database-file-format. It also described in the step 9 in https://github.com/poanetwork/bridge-ui/blob/master/README.md.

In your case the database file should be as following:
```
home_contract_address = "0xE04d6A4a971d242aC246637843431E32269DBeC4"
foreign_contract_address = "0x74c2d89A4E15061c6C24a7f8cb11BE43e24464e0"
checked_deposit_relay = 3907634
checked_withdraw_relay = 8238408
checked_withdraw_confirm = 8238408
```
`deployedBlockNumber` was `null` in the database generated by the deployment script that's why I just used the latest block number in `Sokol-testnet`

**Comment by kpulkit29** [comment]
So I should just replace the home and foriegn contract address here right??

**Comment by akolotov** [comment]
> Bridge version??

Did you build it from source code? Or downloaded from https://github.com/poanetwork/poa-bridge/releases? It is important since a specific version of `bridge` process is able to work with a specific version of bridge contracts. Please refer to release notes of particular release.

**Comment by akolotov** [comment]
> So I should just replace the home and foriegn contract address here right??

I already replaced the contract addresses by using addresses from the deployment database you provided above. Please check my example one more time.

**Comment by kpulkit29** [comment]
I followed the steps mentioned in poa-bridge UI github repo

**Comment by kpulkit29** [comment]
Thanks the rust thing is working on terminal now and says waiting for new
withdraws that should get signed

**Comment by kpulkit29** [comment]
So now the only step left is the UI part right?

**Comment by akolotov** [comment]
> So now the only step left is the UI part right?

right

**Comment by kpulkit29** [comment]
Sir thanks a lot for all the help.Me and my CEO have certain questions
about replacing the sokol sidechain with the our sidechain &using our ERC20
instead of POA20.
If its fine with you can we have a skype call to discuss.

Thanks,
Pulkit
