### ISSUE TITLE
Cannot parse config: unknown field ipc

### ISSUE THREAD

**Issue by maxidev** [poanetwork/poa-bridge#52]
INFO:bridge: Parsing cli arguments
INFO:bridge: Loading config
Cannot parse config

Caused by:
  unknown field `ipc`, expected one of `account`, `contract`, `request_timeout`, `poll_interval`, `required_confirmations`, `rpc_host`, `rpc_port`, `password` for key `home`

Anyone else getting this? using file as shown on readme:
---

estimated_gas_cost_of_withdraw = 0
[home]
#account which you specified as validator on Home network
account = "0xETH_ACCOUNT_VALIDATOR_SOKOL" 
#Full  IPC path to your HOME node
ipc = "/Users/USERNAME/sokol-kovan-bridge/sokol-node/sokol-datadir/jsonrpc.ipc"
# How many block confirmation to wait to send a tx
required_confirmations = 0

[home.contract]

bin = "HomeBridge_bytecode.bin"

[foreign]
account = "0xETH_ACCOUNT_VALIDATOR_KOVAN"
ipc = "/Users/USERNAME/sokol-kovan-bridge/kovan-node/kovan-datadir/jsonrpc.ipc"
required_confirmations = 0

[foreign.contract]
bin = "ForeignBridge_bytecode.bin"

[authorities]
accounts = [
  "0xETH_ACCOUNT_VALIDATOR_KOVAN"
]
required_signatures = 1

[transactions]
home_deploy = { gas = 3000000, gas_price = 1000000000 }
foreign_deploy = { gas = 3000000, gas_price = 1000000000 }
deposit_relay = { gas = 3000000, gas_price = 1000000000 }
withdraw_relay = { gas = 3000000, gas_price = 1000000000 }
withdraw_confirm = { gas = 3000000, gas_price = 1000000000 }

**Comment by akolotov** [comment]
the README.md is not updated since last commits. IPC functionality is deprecated in POA version of bridge. We are using RPC instead.

**Comment by igorbarinov** [comment]
@akolotov please create an issue to update the doc

**Comment by akolotov** [comment]
@igorbarinov we already have one: https://github.com/poanetwork/parity-bridge/issues/34.
It was not address since we are waited for RPC functionality integrated. Now it is in so the docs will be updated.

**Comment by igorbarinov** [comment]
I see. Please ask Yurii to update it then and close both issues

**Comment by maxidev** [comment]
Meanwhile if something having the same issue I had to check out to commit (da91da9db70ac7c4a971eb86eab8e7adf6ce4884) to make it work with current sample config files.

**Comment by yrashk** [comment]
The documentation and examples have been updated some time ago to reflect that IPC is no longer used.
